### ISSUE TITLE
Hotfix required: JVM11 instead of JVM17

### ISSUE THREAD

**Issue by Bdegraaf1234** [RADAR-base/kafka-connect-transform-keyvalue#12]
As described in issue #11, we need a hotfix release to resolve the problems caused by release #10

**Comment by Bdegraaf1234** [comment]
For future reference, these jvm mismatches result in unrecognized classes when deploying the containers. Others have [the same issues](https://stackoverflow.com/questions/77009562/strimzi-kafka-connect-cannot-find-my-custom-transformer-but-finds-connector).

```
[2024-04-24 12:39:05,597] ERROR Failed to create connector for /etc/kafka-connect/sink-s3/sink-s3.properties (org.apache.kafka.connect.cli.ConnectStandalone)
[2024-04-24 12:39:05,598] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone)
java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector configuration is invalid and contains the following 2 error(s):
Invalid value org.radarbase.kafka.connect.transforms.CombineKeyValue for configuration transforms.combineKeyValue.type: Class org.radarbase.kafka.connect.transforms.CombineKeyValue could not be found.
Invalid value null for configuration transforms.combineKeyValue.type: Not a Transformation
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:123)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:107)
	at org.apache.kafka.connect.cli.ConnectStandalone.processExtraArgs(ConnectStandalone.java:81)
	at org.apache.kafka.connect.cli.AbstractConnectCli.startConnect(AbstractConnectCli.java:150)
	at org.apache.kafka.connect.cli.AbstractConnectCli.run(AbstractConnectCli.java:94)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:112)
```
